[package]
name = "omr"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
ndarray = "0.17.2"
ort = "2.0.0-rc.11"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
