[package]
name = "omr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"], optional = true }

[features]
cli = ["dep:clap"]

[[bin]]
name = "omr"
path = "src/main.rs"
required-features = ["cli"]